version: '3'

services: 
  user_backend:
    container_name: user_backend
    # build:
    #   context: .
    #   dockerfile: Dockerfile-prod
    image: test_user-backend
    stdin_open: true
    tty: true
    environment:
      - APP_DEBUG_MODE=false
    ports:
      - "5000:5000"
  user_psql:
    container_name: user_psql
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yacs@rpi
      - POSTGRES_DB=main
    ports:
      - 5432:5432
    
