name: Simple Pytest 

on:
  push:
    branches:
      - test/simple

jobs:
  testcode:
    name: Test user_backend with pytest 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-postgresql
        pytest
    - name: Generate coverage report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install pytest-cov
        pip install coveralls
        pytest --cov=.
        coveralls

  testdocker:
    name: Test docker-compose stack
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: testcode
   
    steps:
    - uses: actions/checkout@v2  
    - name: Build complete stack
      run: docker-compose -f docker-compose.staging.yml up -d
    - name: Check containers are running
      run: |
        docker ps -a
        [ $(docker ps -a | awk -F '[[:space:]][[:space:]]+' 'FNR > 1 { print $5 }' | grep -c "Up") -eq 2 ]
    - name: Check api status
      run: curl -s --retry 10 --retry-connrefused http://localhost:5000/
